baseURL = 'https://example.com/' # Update this to your site's URL
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'My New Hugo Site'
theme = 'basic'
paginate = 10
uglyURLs = true

[params]
  author = 'Me'
