baseURL = 'https://arran4.github.io/githubpages/' # Update this to your site's URL
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Hugo GitHub Pages Template'
theme = 'basic'
uglyURLs = true

[pagination]
  pagerSize = 10

[params]
  author = 'Me'
